In [53]:
import numpy as np

In [54]:
arr = np.random.randint(1,99, size=(10,5))
print(arr)

[[35 74 14 20 69]
 [31 93 89 17 82]
 [78 57  3 46 52]
 [ 5 14 33 93  6]
 [29 50 76 89 97]
 [15 69 20 44 34]
 [70  9 68 33 38]
 [30 31 75 30 36]
 [40 83 54 18 83]
 [ 7 10 82 41 19]]


In [55]:
print(arr.shape)
r_arr = arr.reshape(5,10)
print(r_arr)
print(r_arr.shape)

(10, 5)
[[35 74 14 20 69 31 93 89 17 82]
 [78 57  3 46 52  5 14 33 93  6]
 [29 50 76 89 97 15 69 20 44 34]
 [70  9 68 33 38 30 31 75 30 36]
 [40 83 54 18 83  7 10 82 41 19]]
(5, 10)


In [56]:
# Row wise flattening
flatten_arr = r_arr.flatten()
print(flatten_arr)

[35 74 14 20 69 31 93 89 17 82 78 57  3 46 52  5 14 33 93  6 29 50 76 89
 97 15 69 20 44 34 70  9 68 33 38 30 31 75 30 36 40 83 54 18 83  7 10 82
 41 19]


In [57]:
# column wise flattening (use Fortran order for column-major)
c_flatten_arr = np.ravel(r_arr, order="F")
print(c_flatten_arr)

[35 78 29 70 40 74 57 50  9 83 14  3 76 68 54 20 46 89 33 18 69 52 97 38
 83 31  5 15 30  7 93 14 69 31 10 89 33 20 75 82 17 93 44 30 41 82  6 34
 36 19]


In [58]:
# concatenate
a = np.random.randint(1,10,size=(2,3))
b = np.random.randint(20,30,size=(2,3))
print(a)
print(b)


[[7 7 8]
 [2 5 1]]
[[20 21 28]
 [27 23 26]]


In [59]:
con_row = np.concatenate((a,b),axis=0) #axis=0 is row
print(con_row)

[[ 7  7  8]
 [ 2  5  1]
 [20 21 28]
 [27 23 26]]


In [60]:
con_col = np.concatenate((a,b),axis=1)
print(con_col)

[[ 7  7  8 20 21 28]
 [ 2  5  1 27 23 26]]


In [61]:
## tanspose

mat = np.array([
    [2,3,4],
    [5,6,7]
])

traspose = mat.T
print(traspose)

[[2 5]
 [3 6]
 [4 7]]


In [62]:
import numpy as np

# Create a 1D array
arr = np.arange(10)
print(arr)

splitted_arr = np.array_split(arr,3)
print(splitted_arr)

[0 1 2 3 4 5 6 7 8 9]
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [63]:
splitted_arr = np.split(arr,3)

ValueError: array split does not result in an equal division

### Arithmetic operator and mathematical function

In [ ]:
x = np.array([1, 3,4,15])
y = np.array([4,5,6,7])
add = x + y
print(add)

sub = x - y
print(sub)

mul = x*y
print(mul)

div = x/y
print(div)

mod = x%y
print(mod)

[ 5  8 10 22]
[-3 -2 -2  8]
[  4  15  24 105]
[0.25       0.6        0.66666667 2.14285714]
[1 3 4 1]


In [ ]:
#trigonometry and values are in redian

sin_val = np.sin(x)
print(sin_val)
# degree and rad conversion

deg_val = np.rad2deg(sin_val)
print(deg_val)

[ 0.84147098  0.14112001 -0.7568025   0.65028784]
[ 48.21273601   8.08558087 -43.36158891  37.25874871]


In [ ]:
# log
x = np.array([1,2,3,4,5,6,7,8,10])
l = np.log10(x)
print(l)


[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 1.        ]


In [ ]:
# squire root
x = np.array([4,16,20,25])
sqrt = np.sqrt(x)
print(sqrt)

[2.         4.         4.47213595 5.        ]


In [ ]:
x = np.array([4,16,20,25])
summation = np.sum(x)
print(summation)
c_sum = np.cumulative_sum(x)
print(c_sum)

65
[ 4 20 40 65]


In [ ]:
#broadcasting
x = np.array([4,16,20,25])
squire = x**2
print(squire)

[ 16 256 400 625]


In [ ]:
# column size  = must be vector size

matrix = np.array([
    [10,20,30],
    [40,50,60]
])
vector = np.array([1,2,3])

result = matrix * vector
print(result)

[[ 10  40  90]
 [ 40 100 180]]


In [ ]:
#comparison operator
x = np.array([1,2,3])
y = np.array([4,1,5])

greater_than = x > y
print(greater_than)

equal = x==y
print(equal)

[False  True False]
[False False False]


In [ ]:
# all() -> to check if all true
#any() -> if any of them are true

print(np.all(greater_than))
print(np.any(greater_than))

False
True


#### Sorting

In [ ]:
#inplace
x = np.array([5,2,8,9,32,45,3,4,1])
z = x.copy()
print(z)
z.sort()
print(z)

[ 5  2  8  9 32 45  3  4  1]
[ 1  2  3  4  5  8  9 32 45]


In [ ]:
# copy sorting
print(x)
sort_arr = np.sort(x)
print(sort_arr)
print(x)


[ 5  2  8  9 32 45  3  4  1]
[ 1  2  3  4  5  8  9 32 45]
[ 5  2  8  9 32 45  3  4  1]


In [ ]:
matrix = np.array([
    [100,230,30],
    [40,550,60]
])

#row wise sorting axis = 1
row_sort = np.sort(matrix,axis=1)
print(row_sort)
#column wise sort axis = 0
col_sort = np.sort(matrix, axis=0)
print(col_sort)

[[ 30 100 230]
 [ 40  60 550]]
[[ 40 230  30]
 [100 550  60]]


#### Searching

In [ ]:
x = np.array([5,2,8,9,32,45,3,4,1])
index = np.where(x == 9)
print(index)
#np.where(condition, x, y) if true x, otherwise replace with y
index = np.where(x>9,x,100)
print(index)

(array([3]),)
[100 100 100 100  32  45 100 100 100]


In [68]:
matrix = np.array([
    [10,20,30],
    [40,50,60]
])

index = np.where(matrix>30)
print(index)
# amx value index for 1D array
maximun_value_indx = np.argmax(matrix)
print(maximun_value_indx) 

#max value index for 2D using unreavel_index needs 2 arguments index and shape
arr = np.array([
    [10,20,30],
    [40,50,60]
])
row, col = np.unravel_index(np.argmax(arr), arr.shape)
print(row, col)
row_max_indices = np.argmax(arr, axis=1)
print(row_max_indices)
col_max_indices = np.argmax(arr, axis=0)
print(col_max_indices)

(array([1, 1, 1]), array([0, 1, 2]))
5
1 2
[2 2]
[1 1 1]


#### Counting

In [80]:
arr = np.random.randint(1,10,size=(100))
print(arr)

count = np.count_nonzero(arr>6)
print(count)

unique_values,count = np.unique(arr,return_counts=True)
print(unique_values)
print(count)

[8 5 8 8 2 8 3 5 6 9 7 4 4 5 6 7 4 1 1 1 3 9 6 4 9 3 9 5 7 7 4 2 5 3 1 7 2
 2 9 3 4 1 3 9 9 3 7 9 4 8 1 9 1 9 5 5 4 1 1 3 4 8 8 3 7 6 4 3 2 7 7 3 4 3
 9 7 3 3 5 5 5 2 5 9 9 7 2 8 7 6 7 9 5 2 4 1 2 7 9 6]
37
[1 2 3 4 5 6 7 8 9]
[10  9 14 12 12  6 14  8 15]


#### Statistical Methods

In [82]:
#data loading
data = np.genfromtxt(r"data/student_scores.csv",delimiter=',', skip_header=1)
print(data)

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [ ]:
# find the max marks for the math which is first colum 
math_max = np.max(data[:,0])
print(math_max)

science_max = np.max(data[:,1])
print(science_max)

eng_marks = data[::,2:]
print(eng_marks.T)
max_eng_mark = np.max(eng_marks)
print(max_eng_mark)

average_eng_mark = np.mean(eng_marks)
print(average_eng_mark)


# Median is the middle value in a sorted list of numbers.
# If the number of elements is odd, the median is the middle number.
# If it’s even, the median is the average of the two middle numbers.

median_eng_mark = np.median(eng_marks)
print(median_eng_mark) 

95.0
97.0
[[82. 72. 88. 58. 80. 91. 62. 54. 87. 76. 68. 81. 60. 74. 90. 69. 78. 85.
  65. 96.]]
96.0
75.8
77.0


In [92]:
# Standard Deviation
# Standard deviation (SD) measures how spread out the numbers are from the mean (average)
# Low SD → values are close to the mean
# High SD → values are far from the mean

eng_marks = data[::,2:]
print(eng_marks.T)

std_eng_marks = np.std(eng_marks)
print(std_eng_marks)

[[82. 72. 88. 58. 80. 91. 62. 54. 87. 76. 68. 81. 60. 74. 90. 69. 78. 85.
  65. 96.]]
11.749893616539683


In [ ]:
# correlation coefficient
study_hour = np.array([2,3,4,5,6])
exam_score = np.array([70,80,85,90,95])

data = np.array([study_hour,exam_score])
print(data)

cor = np.corrcoef(data)
print(cor)
# numbers are positive and close to 1 , means strong positive correlation

[[ 2  3  4  5  6]
 [70 80 85 90 95]]
[[1.         0.98639392]
 [0.98639392 1.        ]]


#### Linear Aljebra

In [102]:
matrix_a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
matrix_b = np.array([
    [10,11,12],
    [13,14,15],
    [16,17,18]
])
#just element to element multiplication
mul = matrix_a * matrix_b
print(mul)

# real life matrix multiplication
dot_product = np.dot(matrix_a,matrix_b)
print(dot_product)
#trace
print(np.trace(dot_product)) # 84 + 216 + 366 = 666
#determinant
print(np.linalg.det(matrix_b))

#rank 
print(np.linalg.matrix_rank(matrix_b))


[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
666
0.0
2
