In [14]:
arr = [1,2,3]
print(arr*5)

arr = [x*5 for x in arr]
print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [15]:
import numpy as np
arr1 = np.array([1,2,3])

arr1 = arr1*5
print(arr1)

[ 5 10 15]


In [16]:
arr1 = np.array([20,34,56,72])
print(type(arr1))
print("Dimension:",arr1.ndim)
print("Shape:",arr1.shape)
print("Size:",arr1.size)
print("---------------------------------------")
#2D array
arr2 = np.array(
    [
        [1,2,3],
        [5,6,7]
    ]
)

print(arr2)
print("Dimension:",arr2.ndim)
print("Shape:",arr2.shape)
print("Size:",arr2.size)
print("---------------------------------------")
#3D array
arr3 = np.array([
    # First 2D array
    [
        # First row
        [1,2,3],
        # Second row
        [4,5,6],
        # Third row
        [7,8,9]
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ],
    [
        [19,20,21],
        [22,23,24],
        [25,26,27]
    ]
])

print(arr3)
print("Dimension:",arr3.ndim)
print("Shape:",arr3.shape)
print("Size:",arr3.size)

<class 'numpy.ndarray'>
Dimension: 1
Shape: (4,)
Size: 4
---------------------------------------
[[1 2 3]
 [5 6 7]]
Dimension: 2
Shape: (2, 3)
Size: 6
---------------------------------------
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Dimension: 3
Shape: (3, 3, 3)
Size: 27


In [17]:
arr = np.array([1,2,3.45,'6'])
print(arr.dtype)

<U32


In [18]:
arr = np.array([1,2,3,400],dtype=np.int8)
print(arr.dtype)

OverflowError: Python integer 400 out of bounds for int8

In [ ]:
arr = np.array([1,2,3,400],dtype=np.int16)
print(arr.dtype)

int16


In [ ]:
arr = np.array([1,2,3,400])
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr.dtype)

int64
int16


### ndarray creation from existing data

In [ ]:
lst = [1,2,3,4,500.67]
print(lst)
arr  = np.array(lst,dtype=np.int32)
print(arr)
print(type(arr))
print(arr.dtype)

[1, 2, 3, 4, 500.67]
[  1   2   3   4 500]
<class 'numpy.ndarray'>
int32


In [ ]:
lst = [1,3,4,5,True,False,"Hello"]
# mixed data types will be converted to a upcasting type
arr = np.array(lst)
print(arr)
print(arr.dtype)

['1' '3' '4' '5' 'True' 'False' 'Hello']
<U21


In [ ]:
#tuple to array
tup = (1,2,3,4,5)
arr = np.array(tup, dtype=np.int32)
print(arr)
print(arr.dtype)


[1 2 3 4 5]
int32


In [ ]:
# Set
s = {1,2,3,4,5}
arr = np.array(list(s), dtype=np.int32)
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)

[1 2 3 4 5]
int32
<class 'numpy.ndarray'>
1
(5,)


In [ ]:
# dictionary to array
d = {'a':1, 'b':2, 'c':3}
karr = np.array(list(d.keys()))

print(karr)
print(karr.dtype)
print(type(karr))
print(karr.ndim)
print(karr.shape)

print("----- Values -----")
varr = np.array(list(d.values()), dtype=np.int32)

print(varr)
print(varr.dtype)
print(type(varr))
print(varr.ndim)
print(varr.shape)


items = d.items()
print(items)
iarr = np.array(list(items))
print(iarr)
print(iarr.dtype)
print(type(iarr))
print(iarr.ndim)    
print(iarr.shape)

['a' 'b' 'c']
<U1
<class 'numpy.ndarray'>
1
(3,)
----- Values -----
[1 2 3]
int32
<class 'numpy.ndarray'>
1
(3,)
dict_items([('a', 1), ('b', 2), ('c', 3)])
[['a' '1']
 ['b' '2']
 ['c' '3']]
<U21
<class 'numpy.ndarray'>
2
(3, 2)


#### ndarray Creation from Scrach

In [ ]:
arr = np.zeros((3,4), dtype=np.int16)
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size) 

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int16
<class 'numpy.ndarray'>
2
(3, 4)
12


In [ ]:
# create a 0 array by coping a array size 
arr = np.zeros_like(arr3)
print(arr)
print(arr.dtype)
print(arr.shape)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
int64
(3, 3, 3)


In [ ]:
# ones
arr = np.ones((4,3), dtype=np.int16)
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size) 

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
int16
<class 'numpy.ndarray'>
2
(4, 3)
12


In [ ]:
arr = np.ones_like(arr3)
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size) 

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
int64
<class 'numpy.ndarray'>
3
(3, 3, 3)
27


In [ ]:
# full
from math import inf


arr = np.full((4,4),10, dtype=np.int16)
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size) 

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
int16
<class 'numpy.ndarray'>
2
(4, 4)
16


In [ ]:
arr = np.full_like(arr3,False, dtype=np.float64)
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size) 

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
float64
<class 'numpy.ndarray'>
3
(3, 3, 3)
27


In [24]:
# Array creation with random values
arr = np.random.rand(2,3)
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size) 

[[0.56637077 0.23021631 0.23368018]
 [0.54382503 0.59374679 0.95059102]]
float64
<class 'numpy.ndarray'>
2
(2, 3)
6


In [26]:
arr = np.random.randint(1,100,(2,3))
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size) 

[[16 66 59]
 [22 91 70]]
int32
<class 'numpy.ndarray'>
2
(2, 3)
6


In [28]:
arr = np.random.uniform(10,20,(5,3))
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size) 

[[11.90386593 10.77233406 17.98945075]
 [12.05712955 13.23336351 19.01608852]
 [14.9945517  11.6672553  11.52434787]
 [18.03836053 13.53831474 11.57722656]
 [18.23337739 13.8627459  16.09730499]]
float64
<class 'numpy.ndarray'>
2
(5, 3)
15


In [31]:
# Array creation with range function
arr = np.arange(5,9,1).reshape(2,2)
print(arr)

[[5 6]
 [7 8]]


In [37]:
arr = np.linspace(1,10,11)
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size) 

[ 1.   1.9  2.8  3.7  4.6  5.5  6.4  7.3  8.2  9.1 10. ]
float64
<class 'numpy.ndarray'>
1
(11,)
11


In [41]:
arr = np.logspace(0,4,5)
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size) 

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]
float64
<class 'numpy.ndarray'>
1
(5,)
5


In [46]:
arr = np.linspace(1,5,6)
print(arr)
larr = np.logspace(1,5,6, base=2)
print(larr)

[1.  1.8 2.6 3.4 4.2 5. ]
[ 2.          3.48220225  6.06286627 10.55606329 18.37917368 32.        ]
