In [24]:
arr = [1,2,3]
print(arr*5)

arr = [x*5 for x in arr]
print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [25]:
import numpy as np
arr1 = np.array([1,2,3])

arr1 = arr1*5
print(arr1)

[ 5 10 15]


In [26]:
arr1 = np.array([20,34,56,72])
print(type(arr1))
print("Dimension:",arr1.ndim)
print("Shape:",arr1.shape)
print("Size:",arr1.size)
print("---------------------------------------")
#2D array
arr2 = np.array(
    [
        [1,2,3],
        [5,6,7]
    ]
)

print(arr2)
print("Dimension:",arr2.ndim)
print("Shape:",arr2.shape)
print("Size:",arr2.size)
print("---------------------------------------")
#3D array
arr3 = np.array([
    # First 2D array
    [
        # First row
        [1,2,3],
        # Second row
        [4,5,6],
        # Third row
        [7,8,9]
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ],
    [
        [19,20,21],
        [22,23,24],
        [25,26,27]
    ]
])

print(arr3)
print("Dimension:",arr3.ndim)
print("Shape:",arr3.shape)
print("Size:",arr3.size)

<class 'numpy.ndarray'>
Dimension: 1
Shape: (4,)
Size: 4
---------------------------------------
[[1 2 3]
 [5 6 7]]
Dimension: 2
Shape: (2, 3)
Size: 6
---------------------------------------
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Dimension: 3
Shape: (3, 3, 3)
Size: 27


In [27]:
arr = np.array([1,2,3.45,'6'])
print(arr.dtype)

<U32


In [28]:
arr = np.array([1,2,3,400],dtype=np.int8)
print(arr.dtype)

OverflowError: Python integer 400 out of bounds for int8

In [ ]:
arr = np.array([1,2,3,400],dtype=np.int16)
print(arr.dtype)

int16


In [ ]:
arr = np.array([1,2,3,400])
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr.dtype)

int64
int16


### ndarray creation from existing data

In [31]:
lst = [1,2,3,4,500.67]
print(lst)
arr  = np.array(lst,dtype=np.int32)
print(arr)
print(type(arr))
print(arr.dtype)

[1, 2, 3, 4, 500.67]
[  1   2   3   4 500]
<class 'numpy.ndarray'>
int32


In [ ]:
lst = [1,3,4,5,True,False,"Hello"]
# mixed data types will be converted to a upcasting type
arr = np.array(lst)
print(arr)
print(arr.dtype)

['1' '3' '4' '5' 'True' 'False' 'Hello']
<U21


In [35]:
#tuple to array
tup = (1,2,3,4,5)
arr = np.array(tup, dtype=np.int32)
print(arr)
print(arr.dtype)


[1 2 3 4 5]
int32


In [38]:
# Set
s = {1,2,3,4,5}
arr = np.array(list(s), dtype=np.int32)
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)

[1 2 3 4 5]
int32
<class 'numpy.ndarray'>
1
(5,)


In [39]:
# dictionary to array
d = {'a':1, 'b':2, 'c':3}
arr = np.array(list(d.values()), dtype=np.int32)
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)

[1 2 3]
int32
<class 'numpy.ndarray'>
1
(3,)
