In [1]:
arr = [1,2,3]
print(arr*5)

arr = [x*5 for x in arr]
print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [2]:
import numpy as np
arr1 = np.array([1,2,3])

arr1 = arr1*5
print(arr1)

[ 5 10 15]


In [4]:
arr1 = np.array([20,34,56,72])
print(type(arr1))
print("Dimension:",arr1.ndim)
print("Shape:",arr1.shape)
print("Size:",arr1.size)
print("---------------------------------------")
#2D array
arr2 = np.array(
    [
        [1,2,3],
        [5,6,7]
    ]
)

print(arr2)
print("Dimension:",arr2.ndim)
print("Shape:",arr2.shape)
print("Size:",arr2.size)
print("---------------------------------------")
#3D array
arr3 = np.array([
    # First 2D array
    [
        # First row
        [1,2,3],
        # Second row
        [4,5,6],
        # Third row
        [7,8,9]
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ],
    [
        [19,20,21],
        [22,23,24],
        [25,26,27]
    ]
])

print(arr3)
print("Dimension:",arr3.ndim)
print("Shape:",arr3.shape)
print("Size:",arr3.size)

<class 'numpy.ndarray'>
Dimension: 1
Shape: (4,)
Size: 4
---------------------------------------
[[1 2 3]
 [5 6 7]]
Dimension: 2
Shape: (2, 3)
Size: 6
---------------------------------------
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Dimension: 3
Shape: (3, 3, 3)
Size: 27
