In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,99, size=(10,5))
print(arr)

[[52 39 87 57 95]
 [82 72 78 49 68]
 [81  3 75 16 67]
 [35 65  2 32 74]
 [71 92 22  6 95]
 [40 68 12 54 64]
 [87 60 39 42 48]
 [55 34 86  8 97]
 [ 6 23  5 41 27]
 [31 35 70 24  6]]


In [3]:
print(arr.shape)
r_arr = arr.reshape(5,10)
print(r_arr)
print(r_arr.shape)

(10, 5)
[[52 39 87 57 95 82 72 78 49 68]
 [81  3 75 16 67 35 65  2 32 74]
 [71 92 22  6 95 40 68 12 54 64]
 [87 60 39 42 48 55 34 86  8 97]
 [ 6 23  5 41 27 31 35 70 24  6]]
(5, 10)


In [4]:
# Row wise flattening
flatten_arr = r_arr.flatten()
print(flatten_arr)

[52 39 87 57 95 82 72 78 49 68 81  3 75 16 67 35 65  2 32 74 71 92 22  6
 95 40 68 12 54 64 87 60 39 42 48 55 34 86  8 97  6 23  5 41 27 31 35 70
 24  6]


In [5]:
# column wise flattening (use Fortran order for column-major)
c_flatten_arr = np.ravel(r_arr, order="F")
print(c_flatten_arr)

[52 81 71 87  6 39  3 92 60 23 87 75 22 39  5 57 16  6 42 41 95 67 95 48
 27 82 35 40 55 31 72 65 68 34 35 78  2 12 86 70 49 32 54  8 24 68 74 64
 97  6]


In [6]:
# concatenate
a = np.random.randint(1,10,size=(2,3))
b = np.random.randint(20,30,size=(2,3))
print(a)
print(b)


[[7 4 7]
 [9 7 5]]
[[21 24 23]
 [23 26 28]]


In [7]:
con_row = np.concatenate((a,b),axis=0) #axis=0 is row
print(con_row)

[[ 7  4  7]
 [ 9  7  5]
 [21 24 23]
 [23 26 28]]


In [8]:
con_col = np.concatenate((a,b),axis=1)
print(con_col)

[[ 7  4  7 21 24 23]
 [ 9  7  5 23 26 28]]


In [9]:
## tanspose

mat = np.array([
    [2,3,4],
    [5,6,7]
])

traspose = mat.T
print(traspose)

[[2 5]
 [3 6]
 [4 7]]


In [10]:
import numpy as np

# Create a 1D array
arr = np.arange(10)
print(arr)

splitted_arr = np.array_split(arr,3)
print(splitted_arr)

[0 1 2 3 4 5 6 7 8 9]
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [11]:
splitted_arr = np.split(arr,3)

ValueError: array split does not result in an equal division

### Arithmetic operator and mathematical function

In [14]:
x = np.array([1, 3,4,15])
y = np.array([4,5,6,7])
add = x + y
print(add)

sub = x - y
print(sub)

mul = x*y
print(mul)

div = x/y
print(div)

mod = x%y
print(mod)

[ 5  8 10 22]
[-3 -2 -2  8]
[  4  15  24 105]
[0.25       0.6        0.66666667 2.14285714]
[1 3 4 1]


In [16]:
#trigonometry and values are in redian

sin_val = np.sin(x)
print(sin_val)
# degree and rad conversion

deg_val = np.rad2deg(sin_val)
print(deg_val)

[ 0.84147098  0.14112001 -0.7568025   0.65028784]
[ 48.21273601   8.08558087 -43.36158891  37.25874871]


In [18]:
# log
x = np.array([1,2,3,4,5,6,7,8,10])
l = np.log10(x)
print(l)


[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 1.        ]


In [20]:
# squire root
x = np.array([4,16,20,25])
sqrt = np.sqrt(x)
print(sqrt)

[2.         4.         4.47213595 5.        ]


In [21]:
x = np.array([4,16,20,25])
summation = np.sum(x)
print(summation)
c_sum = np.cumulative_sum(x)
print(c_sum)

65
[ 4 20 40 65]
