In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,99, size=(10,5))
print(arr)

[[43  4 98 85 34]
 [75 73 85 37 67]
 [71 13 66 58 84]
 [ 2 60 10 94 52]
 [39 86 59 28 15]
 [16 51 40 45 10]
 [53  7 47 52 33]
 [12  6 42 12 95]
 [92 77 75 22 30]
 [18  5 20 96 89]]


In [3]:
print(arr.shape)
r_arr = arr.reshape(5,10)
print(r_arr)
print(r_arr.shape)

(10, 5)
[[43  4 98 85 34 75 73 85 37 67]
 [71 13 66 58 84  2 60 10 94 52]
 [39 86 59 28 15 16 51 40 45 10]
 [53  7 47 52 33 12  6 42 12 95]
 [92 77 75 22 30 18  5 20 96 89]]
(5, 10)


In [4]:
# Row wise flattening
flatten_arr = r_arr.flatten()
print(flatten_arr)

[43  4 98 85 34 75 73 85 37 67 71 13 66 58 84  2 60 10 94 52 39 86 59 28
 15 16 51 40 45 10 53  7 47 52 33 12  6 42 12 95 92 77 75 22 30 18  5 20
 96 89]


In [5]:
# column wise flattening (use Fortran order for column-major)
c_flatten_arr = np.ravel(r_arr, order="F")
print(c_flatten_arr)

[43 71 39 53 92  4 13 86  7 77 98 66 59 47 75 85 58 28 52 22 34 84 15 33
 30 75  2 16 12 18 73 60 51  6  5 85 10 40 42 20 37 94 45 12 96 67 52 10
 95 89]


In [6]:
# concatenate
a = np.random.randint(1,10,size=(2,3))
b = np.random.randint(20,30,size=(2,3))
print(a)
print(b)


[[4 5 9]
 [4 8 3]]
[[21 20 21]
 [22 20 25]]


In [7]:
con_row = np.concatenate((a,b),axis=0) #axis=0 is row
print(con_row)

[[ 4  5  9]
 [ 4  8  3]
 [21 20 21]
 [22 20 25]]


In [8]:
con_col = np.concatenate((a,b),axis=1)
print(con_col)

[[ 4  5  9 21 20 21]
 [ 4  8  3 22 20 25]]


In [9]:
## tanspose

mat = np.array([
    [2,3,4],
    [5,6,7]
])

traspose = mat.T
print(traspose)

[[2 5]
 [3 6]
 [4 7]]


In [12]:
import numpy as np

# Create a 1D array
arr = np.arange(10)
print(arr)

splitted_arr = np.array_split(arr,3)
print(splitted_arr)

[0 1 2 3 4 5 6 7 8 9]
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [13]:
splitted_arr = np.split(arr,3)

ValueError: array split does not result in an equal division